version: '3'

services:
  web:
    container_name: nginx
    image: nginx:1.25.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/site-available/keycloak-http.conf:/etc/nginx/conf.d/keycloak.conf ## HTTP
      # - ./conf/keycloak.conf:/etc/nginx/conf.d/keycloak.conf ## HTTPS
    networks:
      - public
  database:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-9uvEJqmzkZqpwiWGxRdn}
    volumes:
       - "./database/init:/docker-entrypoint-initdb.d:ro"
       - './database/data:/var/lib/mysql'
    ports:
      - "3306"
    restart: unless-stopped
    networks:
      - private
    command: --default-authentication-plugin=mysql_native_password
  keycloak:
    container_name: keycloak
    build:
      context: ./conf/olvid
      dockerfile: Dockerfile
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql/keycloak
      KC_DB_PORT: 3306
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: JUQ7XUG02wZ1gZfXgs5g
      KC_DB_URL_PROPERTIES : '?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: iGY1owXQbbmqZHX2diqV
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8080"
      - "8043"
    entrypoint: ["/bin/sh", "-c", "/opt/keycloak/bin/kc.sh build --db mysql & /opt/keycloak/bin/kc.sh start"]
    networks:
      - private
      - public
    depends_on:
      - database
networks:
  private:
  public:
  